name: Semantic Release

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      SEMANTIC_RELEASE_TOKEN: # The PAT
        required: true
        type: string
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Semantic release
    environment: devops
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
